name: validart
description: A flexible validation library for Dart, inspired by Zod. Supports chaining, custom rules, nullable values, and built-in validators for emails, phones, and more.
version: 0.1.1
repository: https://github.com/edunatalec/validart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

dev_dependencies:
  coverage: ^1.11.1
  lints: ^5.0.0
  test: ^1.25.15

topics:
  - validation
  - zod
